// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: entries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (id, account_id, amount, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, amount, created_at
`

type CreateEntryParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Amount    int64
	CreatedAt time.Time
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.CreatedAt,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
