// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: transfers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (id, sender_id, recipient_id, amount, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, sender_id, recipient_id, amount, created_at
`

type CreateTransferParams struct {
	ID          uuid.UUID
	SenderID    uuid.UUID
	RecipientID uuid.UUID
	Amount      int64
	CreatedAt   time.Time
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer,
		arg.ID,
		arg.SenderID,
		arg.RecipientID,
		arg.Amount,
		arg.CreatedAt,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
